name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install python Dependencies
        run: |
          sudo apt-get update
          python -m venv venv
          source venv/bin/activate    
          pip3 install --upgrade setuptools pip
          pip install -r requirements.txt
          pip install pytest-html-reporter

      - name: Install GPG Key, Chrome and ChromDriver
        run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - name: Add source.list
        run: echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
      - name: Install Google Chrome Stable
        run: |
          sudo apt-get -y install google-chrome-stable
          
      - name: Install containerd.io and Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y containerd.io docker-ce docker-ce-cli

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Evershop and npm dependencies
        run: |
          npx create-evershop-app myapp
          cd myapp
          npm install

      - name: Start Docker Compose and wait
        run: |
          docker-compose up -d
          docker-compose ps

      - name: Create admin user
        run: |
          docker exec evershop-automation-tests_app_1 npm run user:create -- --email "test@test.fr" --password "123456test123" --name "anouvene"

      - name: Run tests and generate HTML report
        run: |
          source venv/bin/activate
          pytest -rA

      - name: Run tests and generate HTML report
        run: |
          source venv/bin/activate
          pytest

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: pytest_html_report.html

      - name: Shutdown Docker Compose
        run: |
          docker-compose down